# Generated by Django 4.2.30 on 2026-04-24 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("jd_text", models.TextField()),
                ("resume_text", models.TextField()),
                ("jd_skills", models.JSONField(default=list)),
                ("resume_skills", models.JSONField(default=list)),
                ("gap_list", models.JSONField(default=list)),
                ("current_skill_index", models.IntegerField(default=0)),
                ("current_difficulty", models.CharField(default="easy", max_length=10)),
                ("questions_this_skill", models.IntegerField(default=0)),
                ("pending_question", models.TextField(blank=True, default="")),
                ("skill_histories", models.JSONField(default=dict)),
                ("scores", models.JSONField(default=dict)),
                ("learning_plan", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("extracting", "Extracting"),
                            ("assessing", "Assessing"),
                            ("scoring", "Scoring"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="extracting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
