# Generated by Django 4.2.30 on 2026-04-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="depth",
            field=models.CharField(
                choices=[
                    ("snapshot", "Snapshot"),
                    ("standard", "Standard"),
                    ("deep", "Deep Dive"),
                ],
                default="standard",
                max_length=10,
            ),
        ),
    ]
